# SPDX-License-Identifier: MIT OR CC0-1.0
# Bryn (Safire Project)

env:
  node: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:eslint-comments/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:jest/recommended
  - plugin:jest-formatting/recommended
  - plugin:promise/recommended
  - plugin:unicorn/recommended
  - plugin:node/recommended
  - plugin:yml/standard
  - plugin:json/recommended
  - plugin:@getify/proper-arrows/getify-says
  - plugin:functional/recommended
  - plugin:functional/stylitic
  - plugin:typescript-sort-keys/recommended
  - plugin:eslint-comments/recommended
  - plugin:total-functions/recommended
  - plugin:ternary/recommended
  # Airbnb opinions should be near bottom
  - airbnb-typescript/base
  # Replacement rules for Functional Programming
  - plugin:functional/external-recommended
  # Prettier should be last extends
  - prettier
  - plugin:prettier/recommended
  - plugin:yml/prettier
  - plugin:regexp/recommended
ignorePatterns:
  - ".eslintrc.yml"
  - "package.json"
  - "package-lock.json"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: "./tsconfig.json"
  extraFileExtensions: [".yml", ".json"]
plugins:
  - eslint-comments
  - functional
  - "@getify/proper-arrows"
  - header
  - jest
  - jest-formatting
  - json
  - new-with-error
  - node
  - no-constructor-bind
  - no-secrets
  - promise
  - prefer-arrow
  - regexp
  - ternary
  - total-functions
  - "@typescript-eslint"
  - typescript-sort-keys
  - unicorn
  - write-good-comments
  - yml

rules:
  functional/no-class:
    - off
  functional/no-expression-statement:
    - error
    - ignorePattern: ["super", "client.login", "this", "logger", "console"]
  functional/no-this-expression:
    - off
  new-with-error/new-with-error:
    - error
  node/no-unsupported-features/es-syntax:
    - error
    - ignores: ["modules"]
  no-constructor-bind/no-constructor-bind:
    - error
  no-constructor-bind/no-constructor-state:
    - error
  no-secrets/no-secrets:
    - error
  header/header:
    - 2
    - block
    - - " SPDX-License-Identifier: MIT OR CC0-1.0"
      - "Bryn (Safire Project) "
    - 2
  write-good-comments/write-good-comments:
    - warn

settings:
  node:
    tryExtensions:
      - ".js"
      - ".json"
      - ".node"
      - ".ts"
      - ".d.ts"
