# SPDX-License-Identifier: MIT OR CC0-1.0
# Bryn (Safire Project)

image: node:current-alpine3.11

stages:
  - init
  - lint
  - build
  - deploy

before_script:
  - echo "Pipeline ID = $CI_PIPELINE_ID"
  - echo "Project name = $CI_PROJECT_NAME"
  - echo "Build ref = $CI_BUILD_REF_NAME"
  - pwd
  - ls -ail

cache:
  paths:
    - node_modules/

initialize_npm:
  stage: init
  script:
    - npm install
    - echo DISCORD_TOKEN=$DISCORD_TOKEN >> .env

eslint:
  stage: lint
  script:
    - npm install --only-dev
    - npx eslint . --ext .ts --format gitlab

compile_typescript:
  stage: build
  script:
    - npm install --only-dev
    - npx tsc --version
    - npx tsc
  artifacts:
    paths:
      - dist

pm2_start:
  stage: deploy
  script:
    - npx pm2 start dist/index.js
