image: node:16.2.0-alpine3.13

services:
  - docker:20.10.6-dind-rootless

variables:
  SAST_EXPERIMENTAL_FEATURES: "true"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

stages:
  - init
  - lint
  - test
  - build
  - prestaging
  - staging
  - predeploy
  - deploy

before_script:
  - echo "Pipeline ID = $CI_PIPELINE_ID"
  - echo "Project name = $CI_PROJECT_NAME"
  - echo "Build ref = $CI_BUILD_REF_NAME"

cache:
  paths:
    - node_modules/

initialize-npm:
  stage: init
  script:
    - npm install
    - npm install --only-dev

eslint:
  stage: lint
  script:
    - npx eslint . --ext .ts --format gitlab --ignore-path .gitignore
  artifacts:
    reports:
      codequality: gl-codequality.json
  needs: ["initialize-npm"]

sast:
  stage: test
  needs: []

include:
  - template: Security/SAST.gitlab-ci.yml

semgrep-sast:
  cache: {}

semgrep-ci-report:
  stage: test
  image: returntocorp/semgrep-agent:v1
  script:
    - semgrep-agent --publish-deployment $SEMGREP_DEPLOYMENT_ID --publish-token $SEMGREP_APP_TOKEN
  needs: []

jest-junit:
  stage: test
  script:
    - npx jest --ci --reporters=default --reporters=jest-junit --passWithNoTests
  artifacts:
    expire_in: 1 month
    when: always
    reports:
      junit:
        - junit.xml
  needs: ["initialize-npm"]

compile-typescript:
  stage: build
  script:
    - npx tsc
  artifacts:
    expire_in: 1 month
    paths:
      - dist
  needs: ["initialize-npm"]

docker-build:
  stage: prestaging
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY/group/project/image:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY/group/project/image:latest
  needs: ["initialize-npm"]

docker-deploy:
  image: docker:20.10.6
  tags:
    - safire
  stage: staging
  services:
    - docker:20.10.6-dind-rootless
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - echo DISCORD_TOKEN=$DISCORD_TOKEN >> .env
    - docker cp .env $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA:.
    - docker run $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  needs: ["docker-build"]
