image: node:current-alpine3.11

stages:
  - init
  - build
  - deploy

before_script:
  - echo "Pipeline ID = $CI_PIPELINE_ID"
  - echo "Project name = $CI_PROJECT_NAME"
  - echo "Build ref = $CI_BUILD_REF_NAME"
  - pwd
  - ls -ail

cache:
  paths:
    - node_modules/

init:
  stage: init
  script:
    - npm install
    - echo DISCORD_TOKEN=$DISCORD_TOKEN >> .env

build:
  stage: build
  script:
    - npm install --only-dev
    - npx tsc --version
    - npx tsc
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  script:
    - pm2 start dist/index.js
